import '../models/campus_location.dart';
import '../models/checkpoint.dart';

const List<CampusLocation> campusLocations = [
  // Academic Blocks & Library (Academic Keywords: academic, study, class, lecture, ab, engineering, library, book, reading)
  CampusLocation(
    name: 'AB1',
    category: 'Academic Block',
    buildingCode: 'BLK-A1',
    floorCount: 4,
    description:
        'Academic Block 1 houses Engineering lecture halls, Computer Science department offices, smart classrooms, and faculty cabins.',
    distance: '420 m',
    walkingTime: '~5 min',
    isFavorite: true,
    keywords: ['academic', 'study', 'class', 'engineering', 'computer science', 'lecture', 'lab', 'ab1'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from the campus Main Entrance Archway.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk north past the Central Fountain Plaza.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'CS Department Quad', instruction: 'Turn left near the CS Department courtyard.', dx: -0.35, dy: -0.05),
      Checkpoint(label: '4', title: 'AB1 South Entrance', instruction: 'Arrive at AB1 Main Entrance steps.', dx: -0.40, dy: -0.35),
    ],
  ),
  CampusLocation(
    name: 'AB2',
    category: 'Academic Block',
    buildingCode: 'BLK-A2',
    floorCount: 4,
    description:
        'Academic Block 2 features Civil & Mechanical Engineering departments, seminar rooms, and material testing labs.',
    distance: '580 m',
    walkingTime: '~7 min',
    keywords: ['academic', 'study', 'class', 'civil', 'mechanical', 'lecture', 'ab2'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at the Main Gate entrance.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'West Canopy Walkway', instruction: 'Walk past AB1 west canopy walkway.', dx: -0.60, dy: 0.25),
      Checkpoint(label: '3', title: 'Workshop Passage', instruction: 'Cross the inner courtyard walkway.', dx: -0.65, dy: -0.10),
      Checkpoint(label: '4', title: 'AB2 East Archway', instruction: 'Arrive at AB2 Main Entrance.', dx: -0.65, dy: -0.45),
    ],
  ),
  CampusLocation(
    name: 'AB3',
    category: 'Academic Block',
    buildingCode: 'BLK-A3',
    floorCount: 5,
    description:
        'Academic Block 3 contains Electronics, Robotics, Embedded Systems, and Artificial Intelligence laboratories.',
    distance: '710 m',
    walkingTime: '~8 min',
    isFavorite: true,
    keywords: ['academic', 'study', 'class', 'electronics', 'robotics', 'ai', 'lab', 'ab3'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Head north along Central Avenue.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Clock Tower Plaza', instruction: 'Pass the Clock Tower plaza.', dx: -0.45, dy: 0.10),
      Checkpoint(label: '3', title: 'Innovation Annex', instruction: 'Walk past the AI & Robotics Annex.', dx: -0.50, dy: -0.40),
      Checkpoint(label: '4', title: 'AB3 Main Portico', instruction: 'Arrive at AB3 Portico steps.', dx: -0.55, dy: -0.75),
    ],
  ),
  CampusLocation(
    name: 'AB4',
    category: 'Academic Block',
    buildingCode: 'BLK-A4',
    floorCount: 3,
    description:
        'Houses Science departments, basic engineering workshops, humanities classrooms, and research scholar cabins.',
    distance: '790 m',
    walkingTime: '~9 min',
    keywords: ['academic', 'study', 'class', 'science', 'humanities', 'physics', 'chemistry', 'ab4'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk past Central Fountain.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Basic Sciences Quad', instruction: 'Turn right towards Science block.', dx: -0.25, dy: -0.15),
      Checkpoint(label: '4', title: 'AB4 North Gate', instruction: 'Arrive at AB4 Entrance.', dx: -0.20, dy: -0.65),
    ],
  ),
  CampusLocation(
    name: 'MBA Block',
    category: 'Academic Block',
    buildingCode: 'BLK-M1',
    floorCount: 3,
    description:
        'School of Business featuring executive lecture halls, case discussion rooms, and management lounge.',
    distance: '490 m',
    walkingTime: '~6 min',
    keywords: ['academic', 'study', 'class', 'mba', 'business', 'management', 'finance'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Head east from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Management Avenue', instruction: 'Turn left near Dhanalakshmi Bank.', dx: -0.45, dy: 0.40),
      Checkpoint(label: '3', title: 'Executive Lawn', instruction: 'Pass the business school executive lawn.', dx: -0.25, dy: 0.10),
      Checkpoint(label: '4', title: 'MBA Block Portico', instruction: 'Arrive at MBA Block Entrance.', dx: -0.10, dy: -0.25),
    ],
  ),

  // Canteens & Cafes (Food Keywords: food, eat, hungry, lunch, dinner, breakfast, cafe, canteen, coffee, snack)
  CampusLocation(
    name: 'Main Canteen',
    category: 'Canteen',
    buildingCode: 'DIN-01',
    floorCount: 2,
    description:
        'Primary campus food court serving South Indian meals, North Indian dishes, daily specials, fresh juices, and snacks.',
    distance: '280 m',
    walkingTime: '~3 min',
    isFavorite: true,
    keywords: ['food', 'eat', 'hungry', 'canteen', 'lunch', 'dinner', 'breakfast', 'juice', 'snack', 'meals', 'coffee'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Student Center Lawn', instruction: 'Cross the Student Activity Center lawn.', dx: -0.65, dy: 0.55),
      Checkpoint(label: '3', title: 'Canteen Courtyard', instruction: 'Follow paved walkway to Canteen.', dx: -0.55, dy: 0.45),
      Checkpoint(label: '4', title: 'Main Canteen Food Court', instruction: 'Arrive at Main Canteen dining hall.', dx: -0.45, dy: 0.35),
    ],
  ),
  CampusLocation(
    name: 'Millet Cafe',
    category: 'Cafe',
    buildingCode: 'DIN-02',
    floorCount: 1,
    description:
        'Eco-friendly cafe specializing in organic millet snacks, fresh smoothies, herbal teas, and healthy quick bites.',
    distance: '360 m',
    walkingTime: '~4 min',
    keywords: ['food', 'eat', 'hungry', 'cafe', 'millet', 'coffee', 'tea', 'healthy', 'smoothie', 'snack'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Walk towards Campus Garden.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Eco Garden Walkway', instruction: 'Follow the green tree line path.', dx: -0.50, dy: 0.55),
      Checkpoint(label: '3', title: 'Tree Line Pavilion', instruction: 'Walk past open garden benches.', dx: -0.30, dy: 0.48),
      Checkpoint(label: '4', title: 'Millet Cafe Veranda', instruction: 'Arrive at Millet Cafe outdoor terrace.', dx: -0.15, dy: 0.40),
    ],
  ),
  CampusLocation(
    name: 'MBA Canteen',
    category: 'Canteen',
    buildingCode: 'DIN-03',
    floorCount: 1,
    description:
        'Cozy refreshment spot located adjacent to the Management Block offering coffee, rolls, and sandwiches.',
    distance: '510 m',
    walkingTime: '~6 min',
    keywords: ['food', 'eat', 'hungry', 'canteen', 'coffee', 'sandwich', 'snack', 'mba'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Head east along Central Avenue.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Bank Avenue Path', instruction: 'Walk past Bank Branch.', dx: -0.40, dy: 0.45),
      Checkpoint(label: '3', title: 'Management Courtyard', instruction: 'Turn towards Management Block.', dx: -0.20, dy: 0.25),
      Checkpoint(label: '4', title: 'MBA Canteen Counter', instruction: 'Arrive at MBA Canteen seating.', dx: -0.10, dy: 0.05),
    ],
  ),
  CampusLocation(
    name: 'IT Canteen',
    category: 'Canteen',
    buildingCode: 'DIN-04',
    floorCount: 1,
    description:
        'Popular eatery among engineering students for quick rolls, shakes, and fast food items.',
    distance: '570 m',
    walkingTime: '~7 min',
    keywords: ['food', 'eat', 'hungry', 'canteen', 'shake', 'fast food', 'it', 'rolls'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Head west past Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'West Corridor', instruction: 'Walk along the Engineering corridor.', dx: -0.70, dy: 0.35),
      Checkpoint(label: '3', title: 'CS Lab Rear Alley', instruction: 'Turn left behind CS Labs.', dx: -0.65, dy: 0.05),
      Checkpoint(label: '4', title: 'IT Canteen Deck', instruction: 'Arrive at IT Canteen deck.', dx: -0.60, dy: -0.15),
    ],
  ),

  // Library (Academic / Study Keywords: library, study, book, reading, silence, search, paper)
  CampusLocation(
    name: 'Central Library',
    category: 'Library',
    buildingCode: 'LIB-01',
    floorCount: 4,
    description:
        'Four-story central library containing over 100,000 volumes, quiet study zones, digital archives, and computer labs.',
    distance: '850 m',
    walkingTime: '~10 min',
    isFavorite: true,
    keywords: ['academic', 'library', 'study', 'book', 'reading', 'quiet', 'journal', 'research', 'paper'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk past Central Fountain.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Clock Tower Plaza', instruction: 'Turn right at Clock Tower.', dx: -0.20, dy: 0.0),
      Checkpoint(label: '4', title: 'Library Quad Walkway', instruction: 'Follow paved walkway to Library lawn.', dx: 0.0, dy: -0.35),
      Checkpoint(label: '5', title: 'Central Library Entrance', instruction: 'Arrive at Library main entrance.', dx: 0.15, dy: -0.70),
    ],
  ),

  // Hostels (Residence Keywords: hostel, stay, room, residence, sleep, bhavanam, girls, boys)
  CampusLocation(
    name: 'Mythreyi Bhavanam',
    category: 'Girls Hostel',
    buildingCode: 'GH-01',
    floorCount: 5,
    description:
        'Girls residential complex featuring study halls, mess facilities, and 24/7 security desk.',
    distance: '860 m',
    walkingTime: '~11 min',
    keywords: ['hostel', 'stay', 'girls', 'residence', 'room', 'mythreyi', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Walk north along Residential Avenue.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Pass the central promenade gardens.', dx: -0.20, dy: 0.50),
      Checkpoint(label: '3', title: 'Girls Hostel Security Gate', instruction: 'Enter Girls Hostel Complex entrance.', dx: 0.25, dy: 0.35),
      Checkpoint(label: '4', title: 'Mythreyi Courtyard', instruction: 'Arrive at Mythreyi Bhavanam entrance.', dx: 0.65, dy: 0.20),
    ],
  ),
  CampusLocation(
    name: 'Gargi Bhavanam',
    category: 'Girls Hostel',
    buildingCode: 'GH-02',
    floorCount: 5,
    description: 'Modern residence hall for senior female students.',
    distance: '890 m',
    walkingTime: '~11 min',
    keywords: ['hostel', 'stay', 'girls', 'residence', 'gargi', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Walk along Central Promenade.', dx: -0.20, dy: 0.50),
      Checkpoint(label: '3', title: 'East Residential Path', instruction: 'Turn towards Senior Girls Block.', dx: 0.35, dy: 0.40),
      Checkpoint(label: '4', title: 'Gargi Bhavanam Lobby', instruction: 'Arrive at Gargi Bhavanam.', dx: 0.75, dy: 0.35),
    ],
  ),
  CampusLocation(
    name: 'Aditi Bhavanam',
    category: 'Girls Hostel',
    buildingCode: 'GH-03',
    floorCount: 4,
    description: 'Female student residence located on South-East Campus.',
    distance: '910 m',
    walkingTime: '~12 min',
    keywords: ['hostel', 'stay', 'girls', 'residence', 'aditi', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Pass Central Promenade.', dx: -0.20, dy: 0.50),
      Checkpoint(label: '3', title: 'South Residence Walkway', instruction: 'Walk down South Walkway.', dx: 0.20, dy: 0.50),
      Checkpoint(label: '4', title: 'Aditi Bhavanam Portico', instruction: 'Arrive at Aditi Bhavanam.', dx: 0.55, dy: 0.45),
    ],
  ),
  CampusLocation(
    name: 'Savitri Bhavanam',
    category: 'Girls Hostel',
    buildingCode: 'GH-04',
    floorCount: 4,
    description: 'Girls residential accommodation block with quiet study garden.',
    distance: '930 m',
    walkingTime: '~12 min',
    keywords: ['hostel', 'stay', 'girls', 'residence', 'savitri', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Follow Central Promenade east.', dx: -0.20, dy: 0.50),
      Checkpoint(label: '3', title: 'East Garden Alley', instruction: 'Turn right into Garden Alley.', dx: 0.30, dy: 0.55),
      Checkpoint(label: '4', title: 'Savitri Bhavanam Gate', instruction: 'Arrive at Savitri Bhavanam.', dx: 0.70, dy: 0.60),
    ],
  ),
  CampusLocation(
    name: 'Kashyapa Bhavanam',
    category: 'Boys Hostel',
    buildingCode: 'BH-01',
    floorCount: 6,
    description:
        'Boys hostel complex with table tennis lounge, courtyard, and attached dining hall.',
    distance: '920 m',
    walkingTime: '~12 min',
    keywords: ['hostel', 'stay', 'boys', 'residence', 'kashyapa', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Pass Fountain Circle.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Sports Avenue Junction', instruction: 'Cross Sports Avenue.', dx: 0.10, dy: 0.0),
      Checkpoint(label: '4', title: 'Boys Hostel Security Arch', instruction: 'Pass Boys Hostel security desk.', dx: 0.35, dy: -0.10),
      Checkpoint(label: '5', title: 'Kashyapa Bhavanam Block', instruction: 'Arrive at Kashyapa Bhavanam.', dx: 0.60, dy: -0.20),
    ],
  ),
  CampusLocation(
    name: 'Vasishta Bhavanam',
    category: 'Boys Hostel',
    buildingCode: 'BH-02',
    floorCount: 6,
    description: 'Boys residence hall situated near the sports arena.',
    distance: '950 m',
    walkingTime: '~12 min',
    keywords: ['hostel', 'stay', 'boys', 'residence', 'vasishta', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk past Fountain Circle.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Sports Pavilion Walkway', instruction: 'Turn left along Sports Pavilion.', dx: 0.20, dy: -0.15),
      Checkpoint(label: '4', title: 'Vasishta Bhavanam Quad', instruction: 'Arrive at Vasishta Bhavanam.', dx: 0.80, dy: -0.35),
    ],
  ),
  CampusLocation(
    name: 'Agasthya Bhavanam',
    category: 'Boys Hostel',
    buildingCode: 'BH-03',
    floorCount: 5,
    description: 'Boys student accommodation hall on North-East boundary.',
    distance: '980 m',
    walkingTime: '~13 min',
    keywords: ['hostel', 'stay', 'boys', 'residence', 'agasthya', 'bhavanam'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk towards North-East campus.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'North-East Hostel Road', instruction: 'Follow North-East Hostel Road.', dx: 0.40, dy: -0.30),
      Checkpoint(label: '4', title: 'Agasthya Bhavanam Arch', instruction: 'Arrive at Agasthya Bhavanam.', dx: 0.85, dy: -0.55),
    ],
  ),

  // Banking & ATMs (Money Keywords: atm, bank, money, cash, withdraw, pay, dhanalakshmi, icici, sbi)
  CampusLocation(
    name: 'Dhanalakshmi Bank',
    category: 'Bank',
    buildingCode: 'BNK-01',
    floorCount: 1,
    description:
        'Full-service bank branch for student fee payments, challans, and account services.',
    distance: '310 m',
    walkingTime: '~4 min',
    keywords: ['bank', 'money', 'cash', 'fee', 'dhanalakshmi', 'account', 'deposit', 'pay'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Student Center Plaza', instruction: 'Walk past Student Center.', dx: -0.55, dy: 0.60),
      Checkpoint(label: '3', title: 'Bank Branch Arcade', instruction: 'Arrive at Dhanalakshmi Bank.', dx: -0.30, dy: 0.55),
    ],
  ),
  CampusLocation(
    name: 'Dhanalakshmi ATM 1',
    category: 'ATM',
    buildingCode: 'ATM-01',
    floorCount: 1,
    description: '24/7 ATM booth located near the Main Canteen.',
    distance: '280 m',
    walkingTime: '~3 min',
    keywords: ['atm', 'money', 'cash', 'withdraw', 'pay', 'dhanalakshmi'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Food Court Corridor', instruction: 'Walk down Food Court Corridor.', dx: -0.60, dy: 0.50),
      Checkpoint(label: '3', title: 'ATM Kiosk 1', instruction: 'Arrive at Dhanalakshmi ATM 1.', dx: -0.40, dy: 0.40),
    ],
  ),
  CampusLocation(
    name: 'Dhanalakshmi ATM 2',
    category: 'ATM',
    buildingCode: 'ATM-02',
    floorCount: 1,
    description: '24/7 ATM booth located near Academic Block 1.',
    distance: '440 m',
    walkingTime: '~5 min',
    keywords: ['atm', 'money', 'cash', 'withdraw', 'pay', 'dhanalakshmi', 'ab1'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'AB1 South Junction', instruction: 'Walk towards AB1 South entrance.', dx: -0.50, dy: 0.0),
      Checkpoint(label: '3', title: 'ATM Kiosk 2', instruction: 'Arrive at Dhanalakshmi ATM 2.', dx: -0.45, dy: -0.30),
    ],
  ),
  CampusLocation(
    name: 'ICICI ATM',
    category: 'ATM',
    buildingCode: 'ATM-03',
    floorCount: 1,
    description: 'ATM machine located near the Student Center.',
    distance: '180 m',
    walkingTime: '~2 min',
    isFavorite: true,
    keywords: ['atm', 'money', 'cash', 'withdraw', 'icici', 'pay'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Student Center Walkway', instruction: 'Walk 150m straight towards Student Center.', dx: -0.65, dy: 0.58),
      Checkpoint(label: '3', title: 'ICICI ATM Booth', instruction: 'Arrive at ICICI ATM booth.', dx: -0.55, dy: 0.50),
    ],
  ),
  CampusLocation(
    name: 'SBI ATM',
    category: 'ATM',
    buildingCode: 'ATM-04',
    floorCount: 1,
    description: 'State Bank of India 24/7 ATM booth near Central Library.',
    distance: '840 m',
    walkingTime: '~10 min',
    keywords: ['atm', 'money', 'cash', 'withdraw', 'sbi', 'state bank', 'pay'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Pass Fountain Circle.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Library Quad Entrance', instruction: 'Walk towards Library steps.', dx: -0.10, dy: -0.20),
      Checkpoint(label: '4', title: 'SBI Kiosk', instruction: 'Arrive at SBI ATM.', dx: 0.10, dy: -0.60),
    ],
  ),

  // Sports & Gym (Sports Keywords: sports, play, ground, football, cricket, swim, gym, fitness)
  CampusLocation(
    name: 'Main Ground',
    category: 'Sports Ground',
    buildingCode: 'SPT-01',
    floorCount: 1,
    description:
        'Full-size athletic ground with 400m running track, football pitch, cricket nets, and floodlights for evening practice.',
    distance: '680 m',
    walkingTime: '~8 min',
    keywords: ['sports', 'play', 'ground', 'football', 'cricket', 'run', 'track', 'fitness', 'gym'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk north past Fountain Circle.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Sports Complex Arch', instruction: 'Turn right at Sports Complex Arch.', dx: 0.0, dy: -0.30),
      Checkpoint(label: '4', title: 'Athletic Track Entrance', instruction: 'Arrive at Main Ground entrance.', dx: 0.45, dy: -0.85),
    ],
  ),
  CampusLocation(
    name: 'Swimming Pool',
    category: 'Sports Facility',
    buildingCode: 'SPT-02',
    floorCount: 1,
    description:
        'Olympic-standard 8-lane swimming pool with lifeguards and separate timings for students & faculty.',
    distance: '820 m',
    walkingTime: '~10 min',
    keywords: ['sports', 'play', 'swim', 'swimming', 'pool', 'water', 'fitness'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start at Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Pass Fountain Circle.', dx: -0.50, dy: 0.35),
      Checkpoint(label: '3', title: 'Indoor Stadium Road', instruction: 'Follow Indoor Stadium Road.', dx: 0.30, dy: -0.40),
      Checkpoint(label: '4', title: 'Swimming Pool Deck', instruction: 'Arrive at Swimming Pool.', dx: 0.75, dy: -0.75),
    ],
  ),

  // Facilities & Medical (Health Keywords: doctor, health, clinic, medicine, hospital, first aid)
  CampusLocation(
    name: 'Clinic',
    category: 'Medical Facility',
    buildingCode: 'MED-01',
    floorCount: 1,
    description:
        '24/7 Campus Health Center equipped with emergency beds, resident medical officer, and ambulance services.',
    distance: '420 m',
    walkingTime: '~5 min',
    keywords: ['health', 'doctor', 'clinic', 'medicine', 'hospital', 'emergency', 'first aid', 'nurse'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Garden Path', instruction: 'Walk along Central Garden.', dx: -0.40, dy: 0.30),
      Checkpoint(label: '3', title: 'Health Center Driveway', instruction: 'Turn right onto Health Center Driveway.', dx: -0.15, dy: 0.10),
      Checkpoint(label: '4', title: 'Campus Clinic Reception', instruction: 'Arrive at Campus Clinic.', dx: 0.10, dy: -0.10),
    ],
  ),
  CampusLocation(
    name: 'General Store',
    category: 'Store',
    buildingCode: 'STR-01',
    floorCount: 1,
    description:
        'One-stop utility shop selling stationery, printouts, daily toiletries, snacks, and laundry tokens.',
    distance: '290 m',
    walkingTime: '~4 min',
    keywords: ['shop', 'store', 'buy', 'pen', 'paper', 'stationery', 'print', 'snack'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Student Center Lawn', instruction: 'Cross Student Center lawn.', dx: -0.50, dy: 0.45),
      Checkpoint(label: '3', title: 'Utility Store Veranda', instruction: 'Arrive at General Store.', dx: -0.20, dy: 0.15),
    ],
  ),
  CampusLocation(
    name: "Children's Park",
    category: 'Park',
    buildingCode: 'REC-01',
    floorCount: 1,
    description:
        'Lush green open campus park with walking tracks, benches, and recreation space.',
    distance: '450 m',
    walkingTime: '~6 min',
    keywords: ['park', 'garden', 'green', 'walk', 'relax', 'bench'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'East Promenade', instruction: 'Walk down East Promenade.', dx: -0.20, dy: 0.50),
      Checkpoint(label: '3', title: 'Park Fountain Path', instruction: 'Follow Park Fountain path.', dx: 0.05, dy: 0.52),
      Checkpoint(label: '4', title: 'Children\'s Park Lawn', instruction: 'Arrive at Children\'s Park.', dx: 0.30, dy: 0.55),
    ],
  ),
  CampusLocation(
    name: 'Guest House',
    category: 'Guest House',
    buildingCode: 'GST-01',
    floorCount: 2,
    description:
        'Lodging facility for visiting university guests, conference speakers, and visiting parents.',
    distance: '800 m',
    walkingTime: '~10 min',
    keywords: ['guest', 'house', 'stay', 'visitor', 'parent', 'hotel'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Walk down Central Promenade.', dx: -0.20, dy: 0.50),
      Checkpoint(label: '3', title: 'VIP Driveway', instruction: 'Turn right onto VIP Driveway.', dx: 0.40, dy: 0.30),
      Checkpoint(label: '4', title: 'Guest House Lobby', instruction: 'Arrive at Guest House.', dx: 0.80, dy: 0.10),
    ],
  ),

  // Auditoriums & Halls (Hall Keywords: hall, auditorium, event, seminar, amriteshwari, sudhamani)
  CampusLocation(
    name: 'Amriteshwari Hall',
    category: 'Hall',
    buildingCode: 'AUD-01',
    floorCount: 2,
    description:
        'Grand 1,500-seat central auditorium for university convocations, national fests, and cultural events.',
    distance: '500 m',
    walkingTime: '~6 min',
    keywords: ['hall', 'auditorium', 'event', 'amriteshwari', 'fest', 'stage', 'program'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Walk east past Bank.', dx: -0.30, dy: 0.45),
      Checkpoint(label: '3', title: 'Auditorium Plaza', instruction: 'Walk up Auditorium Plaza steps.', dx: 0.0, dy: 0.30),
      Checkpoint(label: '4', title: 'Amriteshwari Hall Portico', instruction: 'Arrive at Amriteshwari Hall.', dx: 0.25, dy: 0.20),
    ],
  ),
  CampusLocation(
    name: 'Sudhamani Hall',
    category: 'Hall',
    buildingCode: 'AUD-02',
    floorCount: 2,
    description:
        'Acoustically treated multi-purpose seminar hall for student workshops and guest lectures.',
    distance: '530 m',
    walkingTime: '~7 min',
    keywords: ['hall', 'seminar', 'workshop', 'sudhamani', 'lecture', 'conference'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Central Promenade', instruction: 'Walk east down Central Promenade.', dx: -0.20, dy: 0.40),
      Checkpoint(label: '3', title: 'Seminar Complex Foyer', instruction: 'Enter Seminar Hall Foyer.', dx: 0.15, dy: 0.20),
      Checkpoint(label: '4', title: 'Sudhamani Hall Entrance', instruction: 'Arrive at Sudhamani Hall.', dx: 0.40, dy: 0.05),
    ],
  ),

  // Labs & Administration (Lab / Job Keywords: lab, workshop, mechanical, electrical, cir, placement, job)
  CampusLocation(
    name: 'Mechanical Labs',
    category: 'Laboratory',
    buildingCode: 'LAB-01',
    floorCount: 2,
    description:
        'Includes Thermal Engineering, CNC machining, CAD/CAM workstations, and Fluid Mechanics labs.',
    distance: '650 m',
    walkingTime: '~8 min',
    keywords: ['lab', 'laboratory', 'mechanical', 'workshop', 'cnc', 'cad', 'thermal'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'West Industrial Road', instruction: 'Walk down West Industrial Road.', dx: -0.70, dy: 0.20),
      Checkpoint(label: '3', title: 'Heavy Machinery Block', instruction: 'Pass Heavy Machinery Block.', dx: -0.72, dy: -0.20),
      Checkpoint(label: '4', title: 'Mechanical Labs Gate', instruction: 'Arrive at Mechanical Labs.', dx: -0.75, dy: -0.55),
    ],
  ),
  CampusLocation(
    name: 'Electrical Labs',
    category: 'Laboratory',
    buildingCode: 'LAB-02',
    floorCount: 2,
    description: 'Electrical machines, power electronics, and circuits testing lab.',
    distance: '670 m',
    walkingTime: '~8 min',
    keywords: ['lab', 'laboratory', 'electrical', 'circuits', 'power', 'electronics'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'West Industrial Road', instruction: 'Walk down West Industrial Road.', dx: -0.70, dy: 0.20),
      Checkpoint(label: '3', title: 'Power Systems Annex', instruction: 'Turn left near Power Systems Annex.', dx: -0.68, dy: -0.25),
      Checkpoint(label: '4', title: 'Electrical Labs Entry', instruction: 'Arrive at Electrical Labs.', dx: -0.70, dy: -0.65),
    ],
  ),
  CampusLocation(
    name: 'CIR Block',
    category: 'Administrative Block',
    buildingCode: 'ADM-01',
    floorCount: 3,
    description:
        'Corporate & Industry Relations center handling campus placements, internship drives, and alumni affairs.',
    distance: '390 m',
    walkingTime: '~5 min',
    keywords: ['cir', 'placement', 'job', 'interview', 'career', 'internship', 'administrative'],
    checkpoints: [
      Checkpoint(label: '1', title: 'Main Gate Entrance', instruction: 'Start from Main Gate.', dx: -0.80, dy: 0.70),
      Checkpoint(label: '2', title: 'Fountain Circle', instruction: 'Walk past Fountain Circle.', dx: -0.40, dy: 0.30),
      Checkpoint(label: '3', title: 'Placement Drive Alley', instruction: 'Walk down Placement Drive Alley.', dx: -0.05, dy: 0.0),
      Checkpoint(label: '4', title: 'CIR Placement Block', instruction: 'Arrive at CIR Block.', dx: 0.25, dy: -0.40),
    ],
  ),
];